### ISSUE TITLE
Getting tons of errors with this library.

### ISSUE THREAD

**Issue by Joshuaph** [vinniefalco/LuaBridge#137]
Hello! I am using c++11 and LUA 5.3.4 and I am currently getting errors on almost every header file of this class. I have already changed line 460 of Stack.h and have included the LUA files on some of the classes. 
For example, almost every lua_State* objects throw me the error: "undefined". Thanks in advanced!
Some screenshots:
![image](https://cloud.githubusercontent.com/assets/26073824/23572242/f52f5a36-002a-11e7-8bea-207ae6fa6f65.png)
![image](https://cloud.githubusercontent.com/assets/26073824/23572252/02263476-002b-11e7-98bb-ac420f870213.png)
![image](https://cloud.githubusercontent.com/assets/26073824/23572259/0af83c02-002b-11e7-84e4-b48b7aa161a8.png)
![image](https://cloud.githubusercontent.com/assets/26073824/23572271/2027efb4-002b-11e7-9e75-6f8bd4a9da6b.png)
![image](https://cloud.githubusercontent.com/assets/26073824/23572500/b1e5fbac-002c-11e7-94cd-e8bc95577967.png)

Edit: Some problems are fixed if i add the luabridge:: prefix like so:
![image](https://cloud.githubusercontent.com/assets/26073824/23572290/4a057c84-002b-11e7-9a0e-7b3b7ae1b6ca.png)

**Comment by Henningstone** [comment]
The luabridge headers do not include the lua headers itself, so you have include them first:
```c++
#include <lua.hpp>
#include <engine/external/luabridge/LuaBridge.h>
```
You should be able to make it work without modifying anything of the luabridge code.

IntelliSense may still show you a bunch of errors because it's not recognizing this solution, but as long as it compiles fine, you can simply ignore these then.
