### ISSUE TITLE
RefCountedPtr and '==' operator

### ISSUE THREAD

**Issue by imekon** [vinniefalco/LuaBridge#181]
If I use find with a RefCountedPtr, like this:

    auto iter = find(_children.begin(), _children.end(), child);
        if (iter != _children.end())
            _children.erase(iter);

I get this error:

    xutility(3520): error C2678: binary '==': no operator found which takes a left-hand operand of type 'luabridge::RefCountedPtr<MakeIt::Node>' (or there is no acceptable conversion)

_children is std::vector<RefCountedPtr<Node>> _children
child is RefCountedPtr<Node> child.

I found this works:

    for (auto iter = _children.begin(); iter != _children.end(); ++iter)
    {
        if (iter->get() == child.get())
        {
           _children.erase(iter);
           break;
        }
    }

is there a way to make std::find work?

**Comment by dmitry-t** [comment]
I agree, that the `operator==` makes sense here, at least for consistency with the std:: shared_ptr (https://en.cppreference.com/w/cpp/memory/shared_ptr/operator_cmp).

The easiest way to make it working is contributing the corresponding changes yourself, of course :)

Otherwise you can use the latter approach or an alternative with a lambda/functor (and wait until I implement the change).
