### ISSUE TITLE
custom error function

### ISSUE THREAD

**Issue by kunitoki** [vinniefalco/LuaBridge#91]
Would be cool to register an error function to be used when calling LuaRef::operator()

```
static int myErrorHandler(lua_State*)
{
    ...
}

luabridge::registerCustomErrorHandler(&myErrorHandler);
```

so when issuing LuaException::pcall, the specific function will be called (so i can register my own traceback in there).

luabind also has something similar, you can provide you own error function http://www.rasterbar.com/products/luabind/docs.html#pcall-errorfunc

**Comment by dmitry-t** [comment]
LuaBridge doesn't have a purpose to wrap every function, e.g. there is no `luabridge::newState ()`.

In order to register a custom handler, it's enough to call the Lua C API function:
```C++
lua_atpanic (L, myErrorHandler);
```

BTW, since #194 an error handler is set up when `getGlobalNamespace ()` is called. This handler throws a C++ exception with an error message taken from Lua. Such behavior should normally cover most of needs.
